# Burns full-narration subtitles onto a freshly assembled reel.
#
# Called by assemble-reel.ps1 and produce-next-reel.ps1 (Invoke-TreatedAssembly)
# right after they write a reel. This is the ONLY place subtitles are burned;
# the callers pass their own narration delay so the timing constant lives with
# the assembly that applied it, not duplicated here.
#
# Timing comes from ffprobe on the real TTS file, never estimated. The ASS is
# generated by src/reelSubtitlesCli.ts (portrait 720x1280 PlayRes, <=15 chars
# per line, char-proportional timing).
#
# Failure policy: best-effort. Publishing must never stop for a subtitle, so on
# any error the original reel is left untouched, a marker records burned=false
# with the error, and the script exits 0. The marker keeps the degradation
# visible to the nightly check instead of silent.
#
# ffmpeg's ass filter mangles Windows drive-letter paths (the colon reads as a
# filter option separator), so the burn runs from inside the reel's directory
# with bare filenames. Proven approach: the VideoForge trial burn on 2026-08-16
# worked exactly this way.

param(
    [Parameter(Mandatory = $true)][string]$ReelPath,
    [Parameter(Mandatory = $true)][string]$NarrationText,
    [Parameter(Mandatory = $true)][string]$TtsFile,
    [int]$DelayMs = 500
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

function Get-MediaSeconds([string]$path) {
    $probeOut = & ffprobe -v error -show_entries format=duration -of csv=p=0 $path 2>&1
    $probeExit = $LASTEXITCODE
    $raw = @($probeOut | Select-Object -First 1)[0]
    $seconds = 0.0
    if ($probeExit -ne 0 -or -not [double]::TryParse([string]$raw, [Globalization.NumberStyles]::Float, [Globalization.CultureInfo]::InvariantCulture, [ref]$seconds)) {
        throw "ffprobe returned no duration for $path (exit $probeExit, got '$raw'; $probeOut)"
    }
    return $seconds
}

function Test-StoryFrames([string]$reel) {
    $dir = [IO.Path]::ChangeExtension($reel, $null).TrimEnd('.') + ".frames"
    foreach ($name in @("1-hook.png", "2-early.png", "3-middle.png", "4-close.png")) {
        $frame = Join-Path $dir $name
        if (-not (Test-Path $frame) -or (Get-Item $frame).Length -eq 0) { return $false }
    }
    return $true
}

$marker = "$ReelPath.subs.json"
$narrationTrimmed = $NarrationText.Trim()
if (-not $narrationTrimmed) {
    Write-Host "burn-narration-subs: empty narration, nothing to burn for $ReelPath"
    exit 0
}

$sha = [Security.Cryptography.SHA256]::Create()
try {
    $narrationSha = ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($narrationTrimmed))) -replace '-', '').ToLower()
} finally {
    $sha.Dispose()
}

if (Test-Path $marker) {
    try {
        $existing = Get-Content $marker -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($existing.burned -eq $true -and $existing.narration_sha256 -eq $narrationSha) {
            if (Test-StoryFrames $ReelPath) {
                Write-Host "burn-narration-subs: already burned for this narration, skipping $ReelPath"
                exit 0
            }
            Write-Host "burn-narration-subs: already burned but frames missing; extracting $ReelPath"
            try {
                & (Join-Path $PSScriptRoot "extract-reel-frames.ps1") -ReelPath $ReelPath
            } catch {
                Write-Warning "extract-reel-frames failed for ${ReelPath}: $($_.Exception.Message)"
            }
            exit 0
        }
    } catch {
        # Unreadable marker: fall through and re-burn; the new marker replaces it.
    }
}

try {
    if (-not (Test-Path $ReelPath)) { throw "Reel not found: $ReelPath" }
    if (-not (Test-Path $TtsFile)) { throw "TTS file not found: $TtsFile" }

    $audioSeconds = Get-MediaSeconds $TtsFile
    $videoSeconds = Get-MediaSeconds $ReelPath

    $reelDir = Split-Path -Parent $ReelPath
    $baseName = [IO.Path]::GetFileNameWithoutExtension($ReelPath)
    $narrationTxt = Join-Path $reelDir "$baseName.narration.txt"
    $assPath = Join-Path $reelDir "$baseName.ass"
    $oldTmp = Join-Path $reelDir "$baseName.subs-tmp.mp4"
    if (Test-Path $oldTmp) { Remove-Item $oldTmp -Force }
    $tmpOut = Join-Path $reelDir "$baseName.subs-tmp-$PID.mp4"
    if (Test-Path $tmpOut) { Remove-Item $tmpOut -Force }

    [IO.File]::WriteAllText($narrationTxt, $narrationTrimmed, (New-Object Text.UTF8Encoding($false)))

    $audioArg = $audioSeconds.ToString([Globalization.CultureInfo]::InvariantCulture)
    $videoArg = $videoSeconds.ToString([Globalization.CultureInfo]::InvariantCulture)
    $cliOut = & (Join-Path $root "node_modules\.bin\tsx.cmd") (Join-Path $root "src\reelSubtitlesCli.ts") `
        --narration-file $narrationTxt --audio-seconds $audioArg --delay-ms $DelayMs `
        --video-seconds $videoArg --out $assPath 2>&1
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path $assPath)) {
        throw "reelSubtitlesCli failed (exit $LASTEXITCODE): $cliOut"
    }

    $tmpName = Split-Path -Leaf $tmpOut
    Push-Location $reelDir
    try {
        $ffOut = & ffmpeg -v error -y -i "$baseName.mp4" -vf "ass=$baseName.ass" `
            -c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p -c:a copy `
            $tmpName 2>&1
        $ffExit = $LASTEXITCODE
    } finally {
        Pop-Location
    }
    if ($ffExit -ne 0) {
        throw "ffmpeg ass burn failed for $ReelPath (exit $ffExit): $ffOut"
    }
    if (-not (Test-Path $tmpOut) -or (Get-Item $tmpOut).Length -eq 0) {
        throw "ffmpeg ass burn produced no output for $ReelPath (ffmpeg said: $ffOut)"
    }
    Move-Item $tmpOut $ReelPath -Force
    Remove-Item $narrationTxt -Force -ErrorAction SilentlyContinue

    @{
        burned           = $true
        narration_sha256 = $narrationSha
        delay_ms         = $DelayMs
        audio_seconds    = [Math]::Round($audioSeconds, 3)
        video_seconds    = [Math]::Round($videoSeconds, 3)
        cli              = "$cliOut"
        burned_at        = (Get-Date).ToString("o")
    } | ConvertTo-Json | Set-Content $marker -Encoding utf8
    Write-Host "burn-narration-subs: burned narration subtitles onto $ReelPath ($cliOut)"
    # Story frames for the eyes-on acceptance pass (see extract-reel-frames).
    # Best-effort like everything here: frames failing must not cost the reel.
    try {
        & (Join-Path $PSScriptRoot "extract-reel-frames.ps1") -ReelPath $ReelPath
    } catch {
        Write-Warning "extract-reel-frames failed for ${ReelPath}: $($_.Exception.Message)"
    }
    exit 0
} catch {
    $message = $_.Exception.Message
    Write-Warning "burn-narration-subs: FAILED for ${ReelPath}: $message"
    @{
        burned           = $false
        narration_sha256 = $narrationSha
        error            = $message
        failed_at        = (Get-Date).ToString("o")
    } | ConvertTo-Json | Set-Content $marker -Encoding utf8
    exit 0
}
